[package]
name = "roybina1100-cloud/noobhost"
version = "0.1.0"
description = "My Python Web App on Wasmer"

[dependencies]
"python/python" = "*"

[[command]]
name = "script"
runner = "https://webc.org/runner/wasi"
annotations = {
  wasi = {
    main-args = ["main.py"]
  }
}

[[service]]
name = "web"
command = "script"
